actions wip

diff --git a/.github/actions/action_2/action.yml b/.github/actions/action_2/action.yml
--- a/.github/actions/action_2/action.yml
+++ b/.github/actions/action_2/action.yml
@@ -14,48 +14,16 @@ inputs:
 
 # Ejecución de la acción
 runs:
-  # Tipo de ejecución (en este caso, node12)
-  using: "node12"
-  # Comando que se va a ejecutar
-  # Crear un archivo con un mensaje de bienvenida
+  # Tipo de ejecución (en este caso, bash)
+  using: "composite"
+  steps:
+    - name: Crear archivo de bienvenida
   run: |
-    const fs = require('fs');
-    const repository = process.env.INPUT_REPOSITORY;
-    const filePath = 'bienvenida.txt';
-    const message = `Hola, bienvenido al repositorio de ${repository}`;
-
-    fs.writeFile(filePath, message, (err) => {
-      if (err) {
-        console.error(`Error al crear el archivo: ${err}`);
-      } else {
-        console.log(`Archivo creado con éxito: ${filePath}`);
-      }
-    });
+    echo "Hola, bienvenido al repositorio de $INPUT_REPOSITORY" > bienvenida.txt
+    if [ $? -eq 0 ]; then
+      echo "Archivo creado con éxito: bienvenida.txt"
+    else
+      echo "Error al crear el archivo"
+    fi
   # Directorio de trabajo
   working-directory: .
-
-
-## Explicación del bloque run:
-
-## Importar el módulo de sistema de archivos (fs)
-# const fs = require('fs');
-
-## Obtener el nombre del repositorio desde la variable de entorno INPUT_REPOSITORY
-# const repository = process.env.INPUT_REPOSITORY;
-
-## Definir el nombre del archivo a crear
-# const filePath = 'bienvenida.txt';
-
-## Crear un mensaje de bienvenida personalizado con el nombre del repositorio
-# const message = `Hola, bienvenido al repositorio de ${repository}`;
-
-## Crear el archivo con el mensaje de bienvenida
-# fs.writeFile(filePath, message, (err) => {
-#   # Manejar el error en caso de que ocurra
-#   if (err) {
-#     console.error(`Error al crear el archivo: ${err}`);
-#   } else {
-#     # Mostrar un mensaje de éxito al crear el archivo
-#     console.log(`Archivo creado con éxito: ${filePath}`);
-#   }
-# });
