variable wip

diff --git a/.github/workflows/variables_1.yml b/.github/workflows/variables_1.yml
--- a/.github/workflows/variables_1.yml
+++ b/.github/workflows/variables_1.yml
@@ -1,20 +1,27 @@
 name: Variables_1
 
 on:
-  push:
-    branches:
-      - main
+  workflow_dispatch:
 
 jobs:
-  mi_job:
-    runs-on: labs-runner
+  script:
+    runs-on: ubuntu-latest
     steps:
       - name: Definir variables de entorno
         run: |
           echo "MI_VARIABLE_1=valor_1" >> $GITHUB_ENV
           echo "MI_VARIABLE_2=valor_2" >> $GITHUB_ENV
-      - name: Ejecutar comando con variables
+      - name: Crear script
         run: |
-          echo "Valor de MI_VARIABLE_1: $MI_VARIABLE_1"
-          echo "Valor de MI_VARIABLE_2: $MI_VARIABLE_2"
-          ./mi_script.sh $MI_VARIABLE_1 $MI_VARIABLE_2
+          echo "#!/bin/bash" > mi_script.sh
+          echo "if [ $# -ne 2 ]; then" >> mi_script.sh
+          echo "  echo 'Error: se deben pasar dos parámetros'" >> mi_script.sh
+          echo "  exit 1" >> mi_script.sh
+          echo "fi" >> mi_script.sh
+          echo "VAR1=$1" >> mi_script.sh
+          echo "VAR2=$2" >> mi_script.sh
+          echo "echo 'La primera variable es: $VAR1'" >> mi_script.sh
+          echo "echo 'La segunda variable es: $VAR2'" >> mi_script.sh
+          chmod +x mi_script.sh
+      - name: Ejecutar comando con variables
+        run: ./mi_script.sh $MI_VARIABLE_1 $MI_VARIABLE_2
